FROM openjdk:8-jre-alpine


WORKDIR /conseil
COPY ./build/conseil.jar /conseil/
COPY ./build/conseil.conf /conseil/
COPY ./build/logback.xml /conseil/
COPY ./build/runconseil-lorre.sh /conseil/
RUN chmod +x /conseil/runconseil-lorre.sh

EXPOSE 1337

CMD ["/conseil/runconseil-lorre.sh"]
