FROM tezos/tezos:protocol

# RPC
EXPOSE 8732
# P2P
EXPOSE 9732
# P2P Mainnet
EXPOSE 19732

#RUN ["tezos-node", "config", "--data-dir", "/tezos-node-data"]
CMD ["tezos-node", "--history-mode", "archive"]
