FROM node:11.1-stretch

WORKDIR /usr/src/app

COPY ./build ./build
COPY ./public ./public
COPY ./src ./src

COPY ./package.json ./
COPY ./package-lock.json ./
COPY ./config-overrides.js ./
COPY ./tsconfig.json ./
COPY ./tslint.json ./

RUN npm install

EXPOSE 3000

CMD [ "npm", "start" ]
