version: '3'

services:

  tezos-node:
    image: tezos/tezos:latest-release
    restart: always
    ports:
      - "8732:8732"
    expose:
      - 8732
    command: "NODE START COMMAND"
    logging:
      driver: "json-file"

  conseil-postgres:
    image: postgres:11.6
    restart: always
    environment:
      POSTRGES_PASSWORD: "password"
      POSTGRES_USER: "conseil"
      POSTGRES_DB: "conseil"
      POSTGRES_INITDB_ARGS: "--lc-collate=en_US.UTF-8 -E UTF8"
    expose:
      - 5423
    volumes:
      - ../../data/conseil.sql:/docker-entrypoint-initdb.d/conseil.sql
    logging:
      driver: "json-file"

  conseil-lorre:
    image: cryptonomictech/conseil:latest
    restart: always
    environment:
      CONSEIL_API_DB_URL: "jdbc:postgresql://conseil-postgres:5432/conseil"
      CONSEIL_API_DB_USER: "conseil"
      CONSEIL_API_DB_PASSWORD: "password"
      CONSEIL_API_DB_NAME: "conseil"
      CONSEIL_LORRE_DB_URL: "jdbc:postgresql://conseil-postgres:5432/conseil"
      CONSEIL_LORRE_DB_USER: "conseil"
      CONSEIL_LORRE_DB_PASSWORD: "password"
      CONSEIL_LORRE_DB_NAME: "conseil"
      CONSEIL_XTZ_ENABLED: "true"
      CONSEIL_XTZ_NODE_HOSTNAME: "tezos-node"
      CONSEIL_XTZ_NODE_PORT: 8732
      CONSEIL_XTZ_NETWORK: "TEZOS NETWORK"
      LORRE_RUNNER_PLATFORM: "tezos"
      LORRE_RUNNER_NETWORK: "TEZOS NETWORK"
      JVM_XMX: "4G"
      CONSEIL_API_KEY: "conseil"
    command: "conseil-lorre"
    logging:
      driver: "json-file"

  conseil-api:
    image: cryptonomictech/conseil:latest
    restart: always
    environment:
      CONSEIL_API_DB_URL: "jdbc:postgresql://conseil-postgres:5432/conseil"
      CONSEIL_API_DB_USER: "conseil"
      CONSEIL_API_DB_PASSWORD: "password"
      CONSEIL_API_DB_NAME: "conseil"
      CONSEIL_LORRE_DB_URL: "jdbc:postgresql://conseil-postgres:5432/conseil"
      CONSEIL_LORRE_DB_USER: "conseil"
      CONSEIL_LORRE_DB_PASSWORD: "password"
      CONSEIL_LORRE_DB_NAME: "conseil"
      CONSEIL_XTZ_ENABLED: "true"
      CONSEIL_XTZ_NODE_HOSTNAME: "tezos-node"
      CONSEIL_XTZ_NODE_PORT: 8732
      CONSEIL_XTZ_NETWORK: "TEZOS NETWORK"
      JVM_XMX: "4G"
      CONSEIL_API_KEY: "conseil"
    command: "conseil-api"
    ports:
      - "4080:80"
    expose:
      - 80
    logging:
      driver: "json-file"

  arronax:
    image: arronax
    restart: always
    ports:
      - "3080:80"
    logging:
      driver: "json-file"
